version: '3.9'

services:
  app:
    image: ssi-hub
    build:
      dockerfile: docker/prod/Dockerfile
    pull_policy: never
    command: 'node /app/dist/main.js'
    depends_on:
      - postgres
      - nats
      - redis
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./private.pem:/app/private.pem
      - ./public.pem:/app/public.pem
    networks:
      - main
    environment:
      DB_HOST: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}

      REDIS_HOST: REDIS
      REDIS_PORT: 6379

      NATS_CLIENTS_URL: nats:4222
      NATS_ENVIRONMENT_NAME: ewf-dev

      ROOT_DOMAIN: iam.ewc
      CHAIN_ID: 73799
      CHAIN_NAME: volta
      ENS_URL: https://volta-rpc-vkn5r5zx4ke71f9hcu0c.energyweb.org
      PUBLIC_RESOLVER_ADDRESS: 0x0a97e07c4Df22e2e31872F20C5BE191D5EFc4680
      ENS_REGISTRY_ADDRESS: 0xd7CeF70Ba7efc2035256d828d5287e2D285CD1ac
      DID_REGISTRY_ADDRESS: 0xC15D5A57A8Eb0e1dCBE5D88B8f9a82017e5Cc4AF
      DOMAIN_NOTIFIER_ADDRESS: 0xeea658026d6CDede4380D3aD030beAC911758A93
      RESOLVER_V1_ADDRESS: 0xf5EA22c1F799d425356c2aab2004200Ab4490D2b
      RESOLVER_V2_ADDRESS: 0xcf72f16Ab886776232bea2fcf3689761a0b74EfE
      CHAIN_REQUEST_ATTEMPTS: 5

      ASSETS_MANAGER_ADDRESS: 0x84d0c7284A869213CB047595d34d6044d9a7E14A
      ASSETS_SYNC_INTERVAL_IN_HOURS: 10
      ASSETS_SYNC_HISTORY_INTERVAL_IN_HOURS: 21
      ASSETS_SYNC_ENABLED: true

      DIDDOC_SYNC_INTERVAL_IN_HOURS: 1
      DID_SYNC_ENABLED: false
      ENS_SYNC_INTERVAL_IN_HOURS: 1
      ENS_SYNC_ENABLED: false
      DID_SYNC_MODE_FULL: false

      ENABLE_AUTH: true
      JWT_PRIVATE_KEY_PATH: /app/private.pem
      JWT_PUBLIC_KEY_PATH: /app/public.pem
      STRATEGY_CACHE_SERVER: http://localhost:3000/v1/
      STRATEGY_PRIVATE_KEY: eab5e5ccb983fad7bf7f5cb6b475a7aea95eff0c6523291b0c0ae38b5855459c
      BLOCKNUM_AUTH_ENABLED: true
      STRATEGY_NUM_BLOCKS_BACK: 10
      JWT_ACCESS_TOKEN_EXPIRES_IN: 1d
      JWT_REFRESH_TOKEN_EXPIRES_IN: 1d
      SIWE_NONCE_EXPIRES_IN: 1m
      JWT_ACCESS_TOKEN_NAME: token
      JWT_REFRESH_TOKEN_NAME: refreshToken
      RESTRICT_CORS_ORIGINS: false
      ALLOWED_ORIGINS:
      UNIVERSAL_RESOLVER_URL: https://dev.uniresolver.io/1:0/identifiers/
      STATUS_LIST_DOMAIN: http://localhost:3000/v1/

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    networks:
      - main
    volumes:
      - full-postgres-data:/var/lib/postgresql/data
#    ports:
#      - '127.0.0.1:${DB_PORT}:5432'
  nats:
    image: synadia/nats-server:nightly
    volumes:
      - ./config/:/etc/nats
    command: '-c /etc/nats/nats.conf'
    networks:
      - main
#    ports:
#      - '${NATS_CLIENTS_URL}:4222'
#      - '127.0.0.1:8222:8222'
#      - '127.0.0.1:9222:9222'
  redis:
    image: redis:${REDIS_VERSION}
    volumes:
      - full-redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - main
#    ports:
#      - '127.0.0.1:${REDIS_PORT}:6379'
networks:
  main:

volumes:
  full-postgres-data:
  full-redis-data:
