version: '3.4'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    networks:
      - main
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:${DB_PORT}:5432'
  nats:
    image: synadia/nats-server:nightly
    volumes:
      - ./config/:/etc/nats
    command: '-c /etc/nats/nats.conf'
    networks:
      - main
    ports:
      - '${NATS_CLIENTS_URL}:4222'
      - '127.0.0.1:8222:8222'
      - '127.0.0.1:9222:9222'
  redis:
    image: redis:${REDIS_VERSION}
    volumes:
      - dev-redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - main
    ports:
      - '127.0.0.1:${REDIS_PORT}:6379'
networks:
  main:

volumes:
  dev-postgres-data:
  dev-redis-data:
