version: "3.4"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:80
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env.dist
    networks:
      - main
    depends_on:
      - nats
      - redis
  nats:
    container_name: nats
    image: synadia/nats-server:nightly
    volumes:
      - ./config/:/etc/nats
    command: "-c /etc/nats/nats.conf"
    networks:
      - main
    ports:
      - "4222:4222"
      - "9222:9222"
  redis:
    container_name: redis
    image: redis:6.0.8
    command: redis-server --requirepass 'password'
    volumes:
      - $PWD/redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - main
networks:
  main: