iam-cache-server-helm:
  replicaCount: 1

  image:
    repository: "124847487737.dkr.ecr.us-west-2.amazonaws.com/ics-api"
    pullPolicy: IfNotPresent

  imagePullSecrets: [ ]
  nameOverride: "ics"
  fullnameOverride: "ics"

  serviceAccount:
    create: true
    annotations: { }
    name: ""

  podAnnotations: { }

  podSecurityContext: { }
  securityContext: { }

  service:
    type: NodePort
    port: 3000

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:124847487737:certificate/ff4589f5-fb2a-400c-a11a-bbd2e62da334
    hosts:
      - host: identitycache-sandbox.energyweb.org
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ics
                port:
                  number: 80
    tls: [ ]

  config:
    secretRefName: ics-secrets
    configRefName: ics-cm

  sealedSecret:
    enabled: true
    annotations: { }
    encryptedData:
      SENTRY_DNS: AgClaonXKKIy0k6b4bzUvE7ratjKNOF5SukT+TVS9yZRllRSRhCDdZn5dCHHFGwn48H0bYuk68YXhKIbgxkeO74gm+e5BlEs2wQrxtnzDw95/r8pZ1AVFiPCcA+x8YIrPcLSkHinUrmK+7m9MQS1xlAwRqNF8YbF6tuyoMB/uRQ6zRG+FOyECMSZiszltw60TvtQnzE6O7TciJ8dES/ubfy7XI8gbZpBjurkIc0hPqjvlB6SZQDjKCwVonxdGZMTDqKuM5mBYwCRwB6QVUS0jYeiOiRz7RltkeJCnelxw6L/4jL+SAn1kdm2aYCLDauxRJRgolXqWWJxDbvnMuKydLvGKrprRgn9RPNTLxZwGcEqAZaNQDK7p71z1FA4i41fr6sjrgnh40e2m1jwoUozMrD/LWC4by9phk7lRRi3n7XAByh1MwVRE23PuYr6Kd+U+/nqN+OeNdbjGo027GjB+2/Z9zbq8RJ9D0WH5C04IwPYPApyzuQ7SL6N/2QqU9EwI1bDKBO+KBc6qeP7MBUa/FD4f8w5uiSfWO8RcN8XB4+kjuHO52RgEPuB237Wc30eZ5dw4BcLvu4BDwy4LSWwy1uueurk69MSgWVXWhLL4Tr3nyHOC+IqDMDlWGtjt868ZhLswGLbaA+5cPlBLA7jpcxzpXYSKnsHFVEsk9miBR9rPEcNygoJjBbJUZPA6mLQitaO03c64h+pubVCiXRuOT5D23eydOzch1v3yy8VjSrewlZ/R2Jti3lU0NfHZ7XALHAYDZYalhnaGPkUZc8r/HAo5d+i4uEUHco
      STRATEGY_PRIVATE_KEY: AgAjj1Z7jObimrVsBYCFy3aoCbOIbIMlpOXOu0MZmvxJ1SkFfIVgm378SmhCOq6koDU5vRNNqTeryK9CAddTE3ZDWhk4rHLtjYMt4U8cUJKryrHNcmZtxkJ4zd7f4TwDvj475I21Bm4CQ74kGOq+q49/m7XXqnKLif+lssE4MKHI5XNtSfTIPX0ssPLBD/wDbcABybQjGuKQL7xgOQlHpf+zyYZLtGaTX4zI4dlm6uSaU6Zl29JSWDjuVCe7PE05F62D3sOxjDEWJdRvLgU1z2AaHIt5NrBjIbvKoVkvI7uHXHRq320kwZI/riS/4WQNR1jI5u8Epawqrm8YS6E+cXEFtIU/fsRiMZXRCrXvueJA2Nt02xB2w5tKQE6vKZWfoZFlpx1GzS/Z/8Fod5EqQQkYcM99GxY++chygVC13Uqr6bU3bZUYRngjbDO6qzGg6JoduALsnlJT5ggmImIeo2lRPnIhEm2hL95I05HH+r+iNUEY/1nL//MGuaDeES7yY+2qVfPAVxFRE14fAeHZMQJ2UEkNFxrkkij8SSklqgiPkIzaNZPzjTzBbCwN5ZBQn6sE6IvcuEJ+HQ2ywl1V9a8iOn2wOoOzKKX628vd7LxesAst+JdKXGPD2pPngrUdTYXkiAV1CfuU8gv/4DX+WVlkXFmDpt7ymbibIiSN8oM6YD08V4N1JPX3ZSMEIit5MnK/Ii0WMMaIwHpHxHLlfCBIsOM/aWp35Y77oh9e6AB6EG8tP0HNgU8iqIjtiE2q01XoaHg0gjKsiwV4U0R4/Nt8
      ENS_URL: AgBMHI6yU48A0y6bUy6w8nugUjjIHQWR/PJMqsNhcVWHhdLt40PaIEEpDfXdm4oLH8uBYEhHZ2U64mubKUVy23EF2aA75ZYQGUb8KM4CE5Wd9FKERtPkTXJbcZ1QEZETQl9raXQ9ZNFw6gvxLUpgYWXc/ZVV9vqFhiICzl8xX3t076SRQMPlnZyxMFvjkTgHmZY4hNK58kfvkyuFlWZC9e2tcbznGmFj7FLBABdLOHu2G6FuPfhu86pFO61qB95eHLgnxLxRDHdcp5mA75eW7aIyGjAkWWC6By7x6c05tzYpHQxLezxUvhD/M4kOl6dNY6BdtfvpaSmSzgst+OW8ekag8y0ZPLRQwNdHWNVZHEvAedbnuRm44w9KZEak5oKUswHu/zpkfn/Og8Ev/YVeq4QkSSqIGxfGFkIWbLUhIpwnmBK31kMcthGAArtC0JIyk3HJuCaEpP68Wmk/Gmrct8XMziAcbiJue4mxa/A7/bzSGLnjj11VwEEV1Z6cVWvkmF4xnmo+CJ19/VFULmmxkX1GaluzsjplODc4Ci1JEJcLaV/joYT5SsWV0ZFt+VkQ7hPo6wbgyKb/R8geYq2WQrpKpcU5YXvRd/qMsjOzla26h4be9i62rG/BMSBw/npt1bRWLqPMS+L1KNi4RGwCClzW8Gvddy065xor1xL8iKIhQiTY80wgu2lfBzotRA82mCHO59U8M5dvSXhDe6Em6Bjd85xq15La3jl69VxzhBGS6w0h3kvXf98/+SxjO3nwMoA6T2SY/g==

  appValues:
    CHAIN_ID: 73799
    CHAIN_NAME: volta
    NATS_ENVIRONMENT_NAME: ewf-dev
    PUBLIC_RESOLVER_ADDRESS: 0x0a97e07c4Df22e2e31872F20C5BE191D5EFc4680
    ENS_REGISTRY_ADDRESS: 0xd7CeF70Ba7efc2035256d828d5287e2D285CD1ac
    ROOT_DOMAIN: iam.ewc
    DID_REGISTRY_ADDRESS: 0xc15d5a57a8eb0e1dcbe5d88b8f9a82017e5cc4af
    CLAIM_MANAGER_ADDRESS: 0x5339adE9332A604A1c957B9bC1C6eee0Bcf7a031
    DOMAIN_NOTIFIER_ADDRESS: 0xeea658026d6CDede4380D3aD030beAC911758A93
    RESOLVER_V1_ADDRESS: 0xf5EA22c1F799d425356c2aab2004200Ab4490D2b
    RESOLVER_V2_ADDRESS: 0xcf72f16Ab886776232bea2fcf3689761a0b74EfE
    ASSETS_MANAGER_ADDRESS: 0x84d0c7284A869213CB047595d34d6044d9a7E14A
    ASSETS_SYNC_INTERVAL_IN_HOURS: 10
    ASSETS_SYNC_HISTORY_INTERVAL_IN_HOURS: 21
    ASSETS_SYNC_ENABLED: false
    DIDDOC_SYNC_INTERVAL_IN_HOURS: 12
    DID_SYNC_ENABLED: true
    DID_SYNC_MODE_FULL: false
    ENS_SYNC_INTERVAL_IN_HOURS: 11
    ENS_SYNC_ENABLED: true
    ENABLE_AUTH: true
    JWT_PRIVATE_KEY: /app/private.pem
    JWT_PUBLIC_KEY: /app/public.pem
    STRATEGY_CACHE_SERVER: https://identitycache-sandbox.energyweb.org/v1
    STRATEGY_NUM_BLOCKS_BACK: 10
    JWT_ACCESS_TOKEN_EXPIRES_IN: 15m
    JWT_REFRESH_TOKEN_EXPIRES_IN: 1h
    JWT_ACCESS_TOKEN_NAME: token
    JWT_REFRESH_TOKEN_NAME: refreshToken
    STATUS_LIST_DOMAIN: https://identitycache-sandbox.energyweb.org/v1
    CHAIN_REQUEST_ATTEMPTS: 5

  opsValues:
    DB_NAME: ics
    NODE_ENV: production
    UNIVERSAL_RESOLVER_URL: https://dev.uniresolver.io/10/identifiers/
    NATS_VERSION: 2.1.8
    NATS_CLIENTS_URL: iam-cache-server-nats.ics.svc.cluster.local:4222
    LOGS_DIRECTORY: /app/logs
    NESTJS_PORT: 3000
    IPFS_CLIENT_PORT: 5001
    IPFS_CLIENT_PROJECT_SECRET: 9506198a91243f03417aaed60e5eb654
    IPFS_CLIENT_PROJECT_ID: 2DBFBP5zsjfImw1wBPn1Vx08Yd5
    IPFS_CLIENT_HOST: ipfs.infura.io
    DB_MAXIMUM_CONNECTION_POOL: 56 # https://github.com/energywebfoundation/iam-cache-server/blob/develop/README.md#connection-pooling
    SENTRY_ENV: sandbox

  resources:
    limits:
      cpu: 750m
      memory: 1Gi
    requests:
      cpu: 500m
      # High memory request is due to DIDKit usage https://github.com/spruceid/didkit/issues/301
      # We anticipate memory usage to decrease once node v18 is used
      memory: 900Mi

  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 3
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 85

  nodeSelector: { }

  tolerations: [ ]

  affinity: { }
