iam-cache-server-helm:
  replicaCount: 1

  image:
    repository: "124847487737.dkr.ecr.us-west-2.amazonaws.com/ics-api"
    pullPolicy: IfNotPresent

  imagePullSecrets: [ ]
  nameOverride: "ics"
  fullnameOverride: "ics"

  serviceAccount:
    create: true
    annotations: { }
    name: ""

  podAnnotations: { }

  podSecurityContext: { }
  securityContext: { }

  service:
    type: NodePort
    port: 3000

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:124847487737:certificate/ff4589f5-fb2a-400c-a11a-bbd2e62da334
    hosts:
      - host: identitycache-sandbox.energyweb.org
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ics
                port:
                  number: 80
    tls: [ ]

  config:
    secretRefName: ics-secrets
    configRefName: ics-cm

  sealedSecret:
    enabled: true
    annotations: { }
    encryptedData:
      SENTRY_DNS: AgBtTbY6TaVrM7InBy1bC8M/dTImalZAQ1mOpIc+dc1KsFtq8ION1MP49K5GgEJKTFkqc436PMo0VZLsjOGB2hbnam49rHyYiM7ZmtvFrbR94QYSgXZHxKMun8vWVr+zBmUZG4p1P0gxibIUz8CsXyCDdHEEh+rtOLtvulpC/9D9Y0pHokIOu4hfYeqdSqzYRWF9XV9y3zTlilAoGBgpfZAkOH1YiT2CVOcQHM8cPIA1Gjl0yNmJQOhlzCphHrB4odSdpakrLhK2MctRGy0nZqb/SAfVniaYM6TkjLlzN8eTRT29BjFqcGtU1M26k+oC4xACTWeCrzNVZlTXi8Gdx6ZrVg87SjxdI87pPOvjI05XyCy0Eo+BqHK6G454pr5mQUntYBeex0Tzpv6JsBbWniBxcS48ewHd1PkcyhqvT75a9EAVPs94yFmJB2HJ2aS+Nyz3OeXM97IijFsmkbCpvToCrZ/SWDZfsb9qFrUJVGoPe40dB3ECcfNOxcb6yyb4SyYPDTMUF6h0satEBAhaG4MhrlMOEgnNwq129RauV9r5TE+Ns7kDGBIGvIxcJp6m4RnzrqKrjDXjbthrFCqs4Ri9Aw43ym9NmAST6TYer/rhHJ9WGzTTsabFAgyuSbMbkZmw54XV5g6Yxp9NzaFRWqcBogMEP9JJEZo6BfUzeM2dEQY4pxG/YMPiiWRp6FRo8sC08OD7iH8hCloh1Te56FHTRDFSTMHkA2a0SWeS28iLxbDHckiLxZTXtFdr0QSiZnkxwOdleVb0yp0+SUjv23jCxzKBnvZAEbtr
      STRATEGY_PRIVATE_KEY: AgBvt/NLYZ3xm8C86sf+Uv2fGW/WBx1WJ2c9G5at8trVgWUJJn+N+ishCPV9gK4MMLNWrhBOC0YodhCoMrX/w7TEdXO+dvBHWHvoftEjasvgV+LDttIDGMMaIIILBnFGRkKCTVbxbDBN8LcO9bI66pwgnBeLXA8QwV50R1tgDUKvPVT1GpogJklyqq291qDor0CqmsoLIyX+lLhsw4+Ab28DsSf2rGgLj8XfVa3aYFlAM5CgN2CyJC6Blzxh93a1geieMThE3R5RLpRh+APUKcQT6Kv49ENNofwk6wpo0PkA1vPzFF+pI83S2SqkQTihoG59ZlvFfJONLKWkBN/keJT0sCVuFnLze3CmdZQoxIZOI4v2fLewkLYyR+Owag+IOrQfvj2BfcsV8SHMRWQaz01DIN7vIy5fF/rk1XGuL1/MgrwvzWouP10T5p1WLvuSTZeO0qLm/3cu/rjbuIXP23WK51pc1jak8ONvS8asPbk+PrtcBvXTo3O9nzyRS7LHvcww5w7ajZj98egGXuA9j+bS5DqbgkBiASK8zzgnm5fg6YPYqyycA0wp6MiTo2xAzRZpgVX0f3DvJcdKvoxcUzteSNou2Zg360fiZC6cmPqrQ6oLtvo/pV9sZOvriypKJKyrDrY3Q2nQtbu/p6AUgjprQi3osmseGtfNNO5UmQvYxFC/3CHo8FkCADr5D2mvMrQP/9baD7yPdVg1dPIciD2RESqcSqzold2p2mWHggSS1ua9gPN6Rrde9AJo5zYPHmOFmHocM3dF/ZC5bdVvvOJM
      ENS_URL: AgDogSHI4CvlKQEZAeop8qWQ4isVl9prSFdz7VDvSCJZ2M9cBsKfYcKFTZwuxznxGJ6vfNT9gpmNgB2R9sHvv+f0sx7ngK5noqQheAGvA6R5jks/5N+digvPrMAc8bZdrlo1WTedhKThJ/eM5S5jNQnBKbFeoUIrlUWvSRZWDYjMnzJm2HU1SCnO9hni6o0OUVde242b0c+AzKMCMHXTQ9wR5F3u0URuk8RguTScBaREN5brQeZs5hTTrAUZlqAc92an9khQhB8t0JEn4fc4Z4p97LuCVsVsA60GlcAGPy2hLOJXL2Qg7Q3k34ralmDCQBnby7dLFOL2aja0DtcKvhQYmoPlQyS4C1AHWZi8jOWCf9dzEYvDtsf/pkb5wdoqq7DblCsyRSN/w656kIsd992mbhIJMNeIKW64WdYQJ586VQZVxSBhKogXQISfDigHv7BhlyilBbQqHNEppdLNNTPvKhIX/M/efTgdlP0WcXCYWJL8UMW9afQTcS9lSf9od6/HcF2RRt4Lg/PSith2vsj/XOis+UAVIQRcC6ozqV8UVc4vqtrfkdL47MWppCljybbp0kQvKE/dLcXOre+/6ezQHcp8XDJYXWlcwbwuVMDr/W4qohydE1OAOdSznD+EiEq1Uvc178T44qK2QoQ0xan9okleU9UKl/yUKRxI1qnQswcMNNKciOdD43ikrMxfT/nFhi3MiMjec0av+Tx7EK4OuwXf5o8UGEwtspoIo1ftBxf8M858u2DkgZSMQ/KwXauuiExRkA==

    appValues:
      CHAIN_ID: 73799
      CHAIN_NAME: volta
      NATS_ENVIRONMENT_NAME: ewf-dev
      PUBLIC_RESOLVER_ADDRESS: 0x0a97e07c4Df22e2e31872F20C5BE191D5EFc4680
      ENS_REGISTRY_ADDRESS: 0xd7CeF70Ba7efc2035256d828d5287e2D285CD1ac
      ROOT_DOMAIN: iam.ewc
      DID_REGISTRY_ADDRESS: 0xc15d5a57a8eb0e1dcbe5d88b8f9a82017e5cc4af
      CLAIM_MANAGER_ADDRESS: 0x5339adE9332A604A1c957B9bC1C6eee0Bcf7a031
      DOMAIN_NOTIFIER_ADDRESS: 0xeea658026d6CDede4380D3aD030beAC911758A93
      RESOLVER_V1_ADDRESS: 0xf5EA22c1F799d425356c2aab2004200Ab4490D2b
      RESOLVER_V2_ADDRESS: 0xcf72f16Ab886776232bea2fcf3689761a0b74EfE
      ASSETS_MANAGER_ADDRESS: 0x84d0c7284A869213CB047595d34d6044d9a7E14A
      ASSETS_SYNC_INTERVAL_IN_HOURS: 10
      ASSETS_SYNC_HISTORY_INTERVAL_IN_HOURS: 21
      ASSETS_SYNC_ENABLED: false
      DIDDOC_SYNC_INTERVAL_IN_HOURS: 12
      DID_SYNC_ENABLED: true
      DID_SYNC_MODE_FULL: false
      ENS_SYNC_INTERVAL_IN_HOURS: 11
      ENS_SYNC_ENABLED: true
      ENABLE_AUTH: true
      JWT_PRIVATE_KEY: /app/private.pem
      JWT_PUBLIC_KEY: /app/public.pem
      STRATEGY_CACHE_SERVER: https://identitycache-sandbox.energyweb.org/v1
      STRATEGY_NUM_BLOCKS_BACK: 10
      JWT_ACCESS_TOKEN_EXPIRES_IN: 15m
      JWT_REFRESH_TOKEN_EXPIRES_IN: 1h
      JWT_ACCESS_TOKEN_NAME: token
      JWT_REFRESH_TOKEN_NAME: refreshToken
      STATUS_LIST_DOMAIN: https://identitycache-sandbox.energyweb.org/v1

    opsValues:
      DB_NAME: ics
      NODE_ENV: production
      IPFS_URL: https://ipfs.infura.io:5001/api/v0/
      UNIVERSAL_RESOLVER_URL: https://dev.uniresolver.io/10/identifiers/
      NATS_VERSION: 2.1.8
      NATS_CLIENTS_URL: iam-cache-server-nats.ics.svc.cluster.local:4222
      LOGS_DIRECTORY: /app/logs
      NESTJS_PORT: 3000
      DB_MAXIMUM_CONNECTION_POOL: 56 # https://github.com/energywebfoundation/iam-cache-server/blob/develop/README.md#connection-pooling
      SENTRY_ENV: sandbox

  resources:
    limits:
      memory: 800Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80

  nodeSelector: { }

  tolerations: [ ]

  affinity: { }
