name: Build and test

# Controls when the action will run.
on:
  pull_request:
    paths-ignore:
      - 'devops/**'
  workflow_dispatch:


jobs:
  deployment:
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{secrets.DB_USERNAME}}
          POSTGRES_DB: ${{secrets.DB_NAME}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
        ports:
          - 5432:5432
        # Add a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        # NATS
      jetstream:
        image: synadia/jsm:latest
        options: >-
          -e JSM_MODE=server


      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5 --entrypoint redis-server


    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm ci

      - name: Generate keys
        run: npm run generate:jwtkeys

      - name: Build the app
        run: npm run build

      - name: Create Nats cluster
        uses: onichandame/nats-action@master
        with:
          port: '4222 4223 4224'

#      - name: Running tests
#        run: npm run test --forceExit
#        env:
#          CI: true
#          ENS_REGISTRY_ADDRESS: ${{secrets.ENS_REGISTRY_ADDRESS}}
#          CHAIN_ID: ${{secrets.CHAIN_ID}}
#          CHAIN_NAME: volta
#          PUBLIC_RESOLVER_ADDRESS: ${{secrets.PUBLIC_RESOLVER_ADDRESS}}
#          RESOLVER_V1_ADDRESS: ${{secrets.RESOLVER_V1_ADDRESS}}
#          DOMAIN_NOTIFIER_ADDRESS: ${{secrets.DOMAIN_NOTIFIER_ADDRESS}}
#          ENS_SYNC_INTERVAL_IN_HOURS: ${{secrets.ENS_SYNC_INTERVAL_IN_HOURS}}
#          ENS_SYNC_ENABLED: ${{secrets.ENS_SYNC_ENABLED}}
#          ENS_URL: ${{secrets.ENS_URL}}
#          ENABLE_AUTH: ${{secrets.ENABLE_AUTH}}
#          REDIS_HOST: localhost
#          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
#          NATS_CLIENTS_URL: localhost:4222
#          STAKING_POOL_FACTORY_ADDRESS: ${{secrets.STAKING_POOL_FACTORY_ADDRESS}}
#          ASSETS_MANAGER_ADDRESS: ${{secrets.ASSETS_MANAGER_ADDRESS}}
#          DID_SYNC_MODE_FULL: false
#          STATUS_LIST_DOMAIN: ${{secrets.STATUS_LIST_DOMAIN}}
#          NATS_ENVIRONMENT_NAME: dev
#          DID_REGISTRY_ADDRESS: ${{secrets.DID_REGISTRY_ADDRESS}}

      - name: Execute DB Schema migrations
        run: npm run migration:test
        env:
          CI: true
          ENS_REGISTRY_ADDRESS: ${{secrets.ENS_REGISTRY_ADDRESS}}
          CHAIN_ID: ${{secrets.CHAIN_ID}}
          CHAIN_NAME: volta
          PUBLIC_RESOLVER_ADDRESS: ${{secrets.PUBLIC_RESOLVER_ADDRESS}}
          RESOLVER_V1_ADDRESS: ${{secrets.RESOLVER_V1_ADDRESS}}
          RESOLVER_V2_ADDRESS: '0xcf72f16Ab886776232bea2fcf3689761a0b74EfE'
          DOMAIN_NOTIFIER_ADDRESS: ${{secrets.DOMAIN_NOTIFIER_ADDRESS}}
          ENS_SYNC_INTERVAL_IN_HOURS: ${{secrets.ENS_SYNC_INTERVAL_IN_HOURS}}
          ENS_URL: ${{secrets.ENS_URL}}
          REDIS_HOST: ${{secrets.REDIS_HOST}}
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
          NATS_CLIENTS_URL: ${{secrets.NATS_CLIENTS_URL}}
          JWT_PUBLIC_KEY_PATH: ${{secrets.JWT_PUBLIC_KEY}}
          JWT_PRIVATE_KEY_PATH: ${{secrets.JWT_PRIVATE_KEY}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: ${{secrets.DB_NAME}}
          JWT_ACCESS_TOKEN_EXPIRES_IN: ${{secrets.JWT_ACCESS_TOKEN_EXPIRES_IN}}
          JWT_REFRESH_TOKEN_EXPIRES_IN: ${{secrets.JWT_REFRESH_TOKEN_EXPIRES_IN}}
          JWT_ACCESS_TOKEN_NAME: ${{secrets.JWT_ACCESS_TOKEN_NAME}}
          JWT_REFRESH_TOKEN_NAME: ${{secrets.JWT_REFRESH_TOKEN_NAME}}
          UNIVERSAL_RESOLVER_URL: ${{secrets.UNIVERSAL_RESOLVER_URL}}
          ROOT_DOMAIN: iam.ewc
          ENS_SYNC_ENABLED: ${{secrets.ENS_SYNC_ENABLED}}
          DID_SYNC_ENABLED: false
          DIDDOC_SYNC_INTERVAL_IN_HOURS: 21
          DID_REGISTRY_ADDRESS: ${{secrets.DID_REGISTRY_ADDRESS}}
          CLAIM_MANAGER_ADDRESS: ${{secrets.CLAIM_MANAGER_ADDRESS}}
          ASSETS_MANAGER_ADDRESS: ${{secrets.ASSETS_MANAGER_ADDRESS}}
          ASSETS_SYNC_INTERVAL_IN_HOURS: ${{secrets.ASSETS_SYNC_INTERVAL_IN_HOURS}}
          ASSETS_SYNC_HISTORY_INTERVAL_IN_HOURS: ${{secrets.ASSETS_SYNC_HISTORY_INTERVAL_IN_HOURS}}
          ASSETS_SYNC_ENABLED: ${{secrets.ASSETS_SYNC_ENABLED}}
          IPFS_URL: ${{secrets.IPFS_URL}}
          NESTJS_PORT: ${{secrets.NESTJS_PORT}}
          STRATEGY_CACHE_SERVER: ${{secrets.STRATEGY_CACHE_SERVER}}
          STRATEGY_PRIVATE_KEY: ${{secrets.STRATEGY_PRIVATE_KEY}}
          STRATEGY_NUM_BLOCKS_BACK: 10
          STAKING_POOL_FACTORY_ADDRESS: ${{secrets.STAKING_POOL_FACTORY_ADDRESS}}
          DID_SYNC_MODE_FULL: false
          ENABLE_AUTH: ${{secrets.ENABLE_AUTH}}
          STATUS_LIST_DOMAIN: ${{secrets.STATUS_LIST_DOMAIN}}
          NATS_ENVIRONMENT_NAME: dev

      - name: Running E2E tests
        run: npm run test:e2e
        env:
          CI: true
          ENS_REGISTRY_ADDRESS: ${{secrets.ENS_REGISTRY_ADDRESS}}
          CHAIN_ID: ${{secrets.CHAIN_ID}}
          CHAIN_NAME: volta
          PUBLIC_RESOLVER_ADDRESS: ${{secrets.PUBLIC_RESOLVER_ADDRESS}}
          RESOLVER_V1_ADDRESS: ${{secrets.RESOLVER_V1_ADDRESS}}
          RESOLVER_V2_ADDRESS: '0xcf72f16Ab886776232bea2fcf3689761a0b74EfE'
          DOMAIN_NOTIFIER_ADDRESS: ${{secrets.DOMAIN_NOTIFIER_ADDRESS}}
          ENS_SYNC_INTERVAL_IN_HOURS: ${{secrets.ENS_SYNC_INTERVAL_IN_HOURS}}
          ENS_URL: ${{secrets.ENS_URL}}
          REDIS_HOST: ${{secrets.REDIS_HOST}}
          REDIS_PORT: ${{ job.services.redis.ports[6379] }}
          NATS_CLIENTS_URL: ${{secrets.NATS_CLIENTS_URL}}
          JWT_PUBLIC_KEY_PATH: ${{secrets.JWT_PUBLIC_KEY}}
          JWT_PRIVATE_KEY_PATH: ${{secrets.JWT_PRIVATE_KEY}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_NAME: ${{secrets.DB_NAME}}
          JWT_ACCESS_TOKEN_EXPIRES_IN: ${{secrets.JWT_ACCESS_TOKEN_EXPIRES_IN}}
          JWT_REFRESH_TOKEN_EXPIRES_IN: ${{secrets.JWT_REFRESH_TOKEN_EXPIRES_IN}}
          JWT_ACCESS_TOKEN_NAME: ${{secrets.JWT_ACCESS_TOKEN_NAME}}
          JWT_REFRESH_TOKEN_NAME: ${{secrets.JWT_REFRESH_TOKEN_NAME}}
          UNIVERSAL_RESOLVER_URL: ${{secrets.UNIVERSAL_RESOLVER_URL}}
          ROOT_DOMAIN: iam.ewc
          ENS_SYNC_ENABLED: ${{secrets.ENS_SYNC_ENABLED}}
          DID_SYNC_ENABLED: false
          DIDDOC_SYNC_INTERVAL_IN_HOURS: 21
          DID_REGISTRY_ADDRESS: ${{secrets.DID_REGISTRY_ADDRESS}}
          CLAIM_MANAGER_ADDRESS: ${{secrets.CLAIM_MANAGER_ADDRESS}}
          ASSETS_MANAGER_ADDRESS: ${{secrets.ASSETS_MANAGER_ADDRESS}}
          ASSETS_SYNC_INTERVAL_IN_HOURS: ${{secrets.ASSETS_SYNC_INTERVAL_IN_HOURS}}
          ASSETS_SYNC_HISTORY_INTERVAL_IN_HOURS: ${{secrets.ASSETS_SYNC_HISTORY_INTERVAL_IN_HOURS}}
          ASSETS_SYNC_ENABLED: ${{secrets.ASSETS_SYNC_ENABLED}}
          IPFS_URL: ${{secrets.IPFS_URL}}
          NESTJS_PORT: ${{secrets.NESTJS_PORT}}
          STRATEGY_CACHE_SERVER: ${{secrets.STRATEGY_CACHE_SERVER}}
          STRATEGY_PRIVATE_KEY: ${{secrets.STRATEGY_PRIVATE_KEY}}
          STRATEGY_NUM_BLOCKS_BACK: 10
          STAKING_POOL_FACTORY_ADDRESS: ${{secrets.STAKING_POOL_FACTORY_ADDRESS}}
          DID_SYNC_MODE_FULL: false
          ENABLE_AUTH: ${{secrets.ENABLE_AUTH}}
          STATUS_LIST_DOMAIN: ${{secrets.STATUS_LIST_DOMAIN}}
          NATS_ENVIRONMENT_NAME: dev
