name: Lint source code

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.8'
      - name: Install modules
        run: npm ci
      - name: Run ESLint
        run: npx eslint --output-file eslint_report.json --format json src
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        if: always()
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint_report.json'
      - name: Run Prettier
        run: npx prettier --check src/**/*.*s e2e/**/*.*s
